AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'aws-crt/native/aws-common-runtime/**/*.rb'

Style/HashSyntax:
  Exclude:
    - 'aws-crt/Rakefile'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'aws-crt/lib/aws-crt/native.rb'

Metrics/BlockLength:
  Exclude:
    - 'aws-crt/Rakefile'
    - '**/*.rake'
    - 'aws-crt/spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'aws-crt/lib/aws-crt.rb'