AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'gems/aws-crt/native/aws-common-runtime/**/*.rb'

Style/HashSyntax:
  Exclude:
    - 'gems/aws-crt/Rakefile'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'gems/aws-crt/lib/aws-crt/native.rb'
    - '**/*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'gems/aws-crt/Rakefile'
    - '**/*.rake'
    - 'gems/aws-crt/spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gems/aws-crt/lib/aws-crt.rb'
    - 'gems/aws-crt-auth/lib/aws-crt-auth.rb'