language: ruby

before_install:
  - gem install bundler -v '< 2'

dist: xenial
group: edge

rvm:
  - 2.6
  - jruby-9.2

sudo: false

env:
  - PURE_RUBY=1
  - KITCHEN_SINK=1

script: >
  (cd aws-crt) &&
  (bundle exec rake spec) &&

