name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  BUILDER_VERSION: v0.6.9
  BUILDER_SOURCE: releases
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-crt-ruby
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

# https://github.com/ruby/setup-ruby
jobs:

#  linux-compat:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        image:
#          - manylinux1-x64
#          - manylinux1-x86
#          - manylinux2014-x64
#          - manylinux2014-x86
#    steps:
#      # We can't use the `uses: docker://image` version yet, GitHub lacks authentication for actions -> packages
#      - name: Build ${{ env.PACKAGE_NAME }}
#        run: |
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u awslabs --password-stdin
#          export DOCKER_IMAGE=docker.pkg.github.com/awslabs/aws-crt-builder/aws-crt-${{ matrix.image }}:${{ env.BUILDER_VERSION }}
#          docker pull $DOCKER_IMAGE
#          docker run --env GITHUB_REF --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_DEFAULT_REGION $DOCKER_IMAGE build -p ${{ env.PACKAGE_NAME }}

  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, jruby, truffleruby]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build ${{ env.PACKAGE_NAME }} + consumers
        run: |
          python -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/releases/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder.pyz')"
          python builder.pyz build -p ${{ env.PACKAGE_NAME }}

  windows-vc14:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.0
          arch: ${{ matrix.arch }}
          uwp: false
          spectre: true
      - name: Build ${{ env.PACKAGE_NAME }} + consumers
        run: |
          python -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/releases/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder.pyz')"
          python builder.pyz build -p ${{ env.PACKAGE_NAME }}

  osx:
    strategy:
      fail-fast: false
      matrix:
        os: [macos]
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, jruby, truffleruby]
    runs-on: macos-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build ${{ env.PACKAGE_NAME }} + consumers
        run: |
          python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
          chmod a+x builder
          ./builder build -p ${{ env.PACKAGE_NAME }} downstream
