name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  BUILDER_VERSION: v0.6.9
  BUILDER_SOURCE: releases
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-crt-ruby
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:

  linux_build:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Generate Linux bins
        env:
          LINUX_BUILD_ONLY: true
        run: |
          python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
          chmod a+x builder
          ./builder build -p ${{ env.PACKAGE_NAME }} downstream
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux_testing_bin
          path: aws-crt-ruby/gems/aws-crt/bin/

  linux_test:
    needs: [linux_build]
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/checkout@v2
      - name: Download Test Bin
        uses: actions/download-artifact@v2
        with:
          name: linux_testing_bin
      - name: Test
        run: |
          bundle install
          bundle exec rake spec_only