name: Lint

on: [push]

jobs:
  clang-format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.8
      with:
        extensions: c,h
        source: ./gems/aws-crt/native/src
        clangFormatVersion: 9
