name: Release

on:
  push:
    branches:
      - '*'  # TODO: Remove after testing...
      - 'master'

env:
  BUILDER_VERSION: v0.6.9
  BUILDER_SOURCE: releases
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-crt-ruby
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        ruby: [2.7]
        arch: [x86, x64]
    runs-on: windows-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Generate Gem artifacts
        run: |
          gem install bundler
          bundle install
          bundle exec rake gem:aws-crt
      - name: Upload gem artifact
        uses: actions/upload-artifact@v2
        with:
          name: pkg
          path: gems/aws-crt/pkg/