name: Rubocop
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Bundle install
        run: |
          bundle install

      - name: Rubocop
        run: bundle exec rubocop -E -S

