name: Rubocop
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Bundle install
        run: |
          gem install bundler
          bundle install

      - name: Rubocop
        run: bundle exec rubocop -E -S
