name: Rubocop
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1

      - name: Rubocop Linter
        uses: andrewmcodes/rubocop-linter-action@73a4572f2fd0bfda08f08a3bae722e996a7e8aa8
        with:
          action_config_path: '.github/config/rubocop_linter_config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}